#!/bin/sh

# Automatically use the repository root, which is the parent directory of .git
REPO_ROOT="$(git rev-parse --show-toplevel)"

# Check for actual changes in the specific directory
if git diff --name-only HEAD@{1} HEAD | grep -q "$REPO_ROOT"
then
    # Check if the system is Linux and systemd is present
    if [ -d "/etc/systemd/system" ]; then
        # Check if the systemd service file is enabled
        if systemctl is-enabled metawrangler.service 2>/dev/null | grep -q 'enabled'; then
            echo "Changes detected in $REPO_ROOT. Restarting the service..."
            sudo systemctl restart metawrangler.service
        else
            echo "Service is not enabled or not found. No action taken."
        fi
    else
        echo "Not a Linux system with systemd or systemd not found. No action taken."
    fi
fi
